version: '3.8'  # Specify the Docker Compose file version

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Use the existing Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db_name
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql  # This line persists the database data

volumes:
  mysql_data:
